---
name: Build & Push (Mono-Repo)
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository_owner }}

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      hello_world_changed: ${{ steps.filter.outputs.hello_world }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            hello_world:
              - 'containers/hello-world/**'
              - 'deploy/**'
              - '.github/workflows/build-push.yml'
              - '.hadolint.yaml'
              - '.yamllint.yml'
              - 'Makefile'

  build-hello-world:
    name: Build & Push hello-world
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.hello_world_changed == 'true' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (multi-arch, SBOM, provenance)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: containers/hello-world/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/hello-world:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/hello-world:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/hello-world:main
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          provenance: mode=min
          sbom: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
