---
name: Lint YAML, Mirror hello-world to GHCR

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  # Ergibt: ghcr.io/<owner>/hello-world:{latest|<SHA>}
  IMAGE_NAME: ${{ github.repository_owner }}/hello-world

jobs:
  lint-yaml:
    name: YAML Syntax prüfen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          file_or_dir: .
          format: github
          strict: false
          no_warnings: false

  mirror:
    name: Mirror zu GHCR (ohne Build)
    runs-on: ubuntu-latest
    needs: lint-yaml
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Mirror hello-world:latest → GHCR
        run: |
          set -euo pipefail
          docker pull hello-world:latest
          docker tag  hello-world:latest $REGISTRY/$IMAGE_NAME:latest
          docker tag  hello-world:latest $REGISTRY/$IMAGE_NAME:${GITHUB_SHA}
          docker push $REGISTRY/$IMAGE_NAME:latest
          docker push $REGISTRY/$IMAGE_NAME:${GITHUB_SHA}
