# .github/workflows/nightly-security-scan.yml
name: Nightly Security Scan
on:
  schedule:
    - cron: "17 2 * * *"  # täglich 02:17 UTC
  workflow_dispatch:

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Scan GHCR Images
        run: |
          set -e
          apps="app-a app-b"
          for a in $apps; do
            img=ghcr.io/${GITHUB_REPOSITORY_OWNER}/$a:latest
            docker pull $img || true
            docker run --rm aquasec/trivy:latest image --severity HIGH,CRITICAL --exit-code 0 "$img"
          done
