name: Security Scan (Trivy)
on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  security-events: write

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository_owner }}/hello-world:latest

jobs:
  trivy-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure image exists (pull)
        run: docker pull $REGISTRY/$IMAGE

      - name: Trivy scan (table)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          scanners: vuln
          vuln-type: os,library
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          format: table
          exit-code: 0

      - name: Trivy scan (SARIF)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          scanners: vuln
          vuln-type: os,library
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          format: sarif
          output: trivy-image.sarif
          exit-code: 0

      - name: Upload SARIF to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image.sarif
