name: YAML Lint

on:
  push:
    paths:
      - "**/*.yml"
      - "**/*.yaml"
  pull_request:
    paths:
      - "**/*.yml"
      - "**/*.yaml"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write  # für PR-Annotations

jobs:
  yamllint:
    name: Run yamllint (errors only)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          file_or_dir: "."
          format: github   # Inline-Annotations im PR/Commit
          strict: false    # ❗️nur Errors brechen ab; Warnungen annotieren, aber Job bleibt grün
